// src/components/PostCard.tsx
import { format } from 'date-fns';
import { Link } from 'gatsby';
import { lighten } from 'polished';
import React from 'react';

import { css } from '@emotion/react';
import styled from '@emotion/styled';

import { colors } from '../styles/colors';
import { PageContext } from '../templates/post';

export interface PostCardProps {
  post: PageContext;
  large?: boolean;
}

export const PostCard: React.FC<PostCardProps> = ({ post, large = false }) => {
  const date = new Date(post.frontmatter.date);
  // 2018-08-20
  const datetime = format(date, 'yyyy-MM-dd');
  // 20 AUG 2018
  const displayDatetime = format(date, 'dd LLL yyyy');

  return (
    <article
      className={`post-card ${large ? 'post-card-large' : ''}`}
      css={[PostCardStyles, large && PostCardLarge]}
    >
      <PostCardContent className="post-card-content">
        <Link className="post-card-content-link" css={PostCardContentLink} to={post.fields.slug}>
          <PostCardHeader className="post-card-header">
            {post.frontmatter.tags && (
              <PostCardPrimaryTag className="post-card-primary-tag">
                {post.frontmatter.tags[0]}
              </PostCardPrimaryTag>
            )}
            <PostCardTitle className="post-card-title">{post.frontmatter.title}</PostCardTitle>
          </PostCardHeader>
          <PostCardExcerpt className="post-card-excerpt">
            <p>{post.frontmatter.excerpt || post.excerpt}</p>
          </PostCardExcerpt>
        </Link>
        <PostCardMeta className="post-card-meta">
          <PostCardBylineContent className="post-card-byline-content">
            <span className="post-card-byline-date">
              <time dateTime={datetime}>{displayDatetime}</time>{' '}
              <span className="bull">&bull;</span> {post.timeToRead} min read
            </span>
          </PostCardBylineContent>
        </PostCardMeta>
      </PostCardContent>
    </article>
  );
};

const PostCardStyles = css`
  position: relative;
  flex: 1 1 301px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  margin: 0 0 40px;
  padding: 0 20px 40px;
  min-height: 220px;
  /* border-bottom: 1px solid color(var(--lightgrey) l(+12%)); */
  border-bottom: 1px solid ${lighten('0.12', colors.lightgrey)};
  background-size: cover;

  @media (prefers-color-scheme: dark) {
    /* border-bottom-color: color(var(--darkmode) l(+8%)); */
    border-bottom-color: ${lighten('0.08', colors.darkmode)};
  }
`;

const PostCardLarge = css`
  @media (min-width: 795px) {
    flex: 1 1 100%;
    flex-direction: row;
    padding-bottom: 40px;
    min-height: 280px;
    border-top: 0;

    :not(.no-image) .post-card-header {
      margin-top: 0;
    }

    .post-card-image-link {
      position: relative;
      flex: 1 1 auto;
      margin-bottom: 0;
      min-height: 380px;
    }

    .post-card-image {
      position: absolute;
      width: 100%;
      height: 100%;
    }

    .post-card-content {
      flex: 0 1 361px;
      justify-content: center;
    }

    .post-card-title {
      margin-top: 0;
      font-size: 3.2rem;
    }

    .post-card-content-link {
      padding: 0 0 0 40px;
    }

    .post-card-meta {
      padding: 0 0 0 40px;
    }

    .post-card-excerpt p {
      margin-bottom: 1.5em;
      font-size: 1.8rem;
      line-height: 1.5em;
    }
  }
`;

const PostCardContent = styled.div`
  flex-grow: 1;
  display: flex;
  flex-direction: column;
`;

const PostCardContentLink = css`
  position: relative;
  display: block;
  /* color: var(--darkgrey); */
  color: ${colors.darkgrey};

  :hover {
    text-decoration: none;
  }
`;

const PostCardPrimaryTag = styled.div`
  margin: 0 0 0.2em;
  /* color: var(--blue); */
  color: ${colors.green};
  font-size: 1.2rem;
  font-weight: 500;
  letter-spacing: 0.2px;
  text-transform: uppercase;
`;

const PostCardTitle = styled.h2`
  margin: 0 0 0.4em;
  line-height: 1.15em;
  transition: color 0.2s ease-in-out;

  @media (prefers-color-scheme: dark) {
    color: rgba(255, 255, 255, 0.85);
  }
`;

const PostCardExcerpt = styled.section`
  font-family: Georgia, serif;

  @media (prefers-color-scheme: dark) {
    /* color: color(var(--midgrey) l(+10%)); */
    color: ${lighten('0.1', colors.midgrey)} !important;
  }
`;

const PostCardMeta = styled.footer`
  display: flex;
  align-items: flex-start;
  padding: 0;
`;

const PostCardBylineContent = styled.div`
  flex: 1 1 50%;
  display: flex;
  flex-direction: column;
  margin: 4px 0 0 10px;
  /* color: color(var(--midgrey) l(+10%)); */
  color: ${lighten('0.1', colors.midgrey)};
  font-size: 1.2rem;
  line-height: 1.4em;
  font-weight: 400;
  letter-spacing: 0.2px;
  text-transform: uppercase;

  span {
    margin: 0;
  }

  a {
    /* color: color(var(--darkgrey) l(+20%)); */
    color: ${lighten('0.2', colors.darkgrey)};
    font-weight: 600;
  }

  @media (prefers-color-scheme: dark) {
    a {
      color: rgba(255, 255, 255, 0.75);
    }
  }
`;

const PostCardHeader = styled.header`
  margin: 15px 0 0;
`;

export const StaticAvatar = css`
  display: block;
  overflow: hidden;
  margin: 0 0 0 -6px;
  width: 34px;
  height: 34px;
  border: #fff 2px solid;
  border-radius: 100%;

  @media (prefers-color-scheme: dark) {
    /* border-color: color(var(--darkgrey) l(+2%)); */
    border-color: ${lighten('0.02', colors.darkgrey)};
  }
`;

export const AuthorProfileImage = css`
  display: block;
  width: 100%;
  height: 100%;
  /* background: color(var(--lightgrey) l(+10%)); */
  background: ${lighten('0.1', colors.lightgrey)};
  border-radius: 100%;
  object-fit: cover;

  @media (prefers-color-scheme: dark) {
    background: ${colors.darkmode};
  }
`;

// src/lib/components/PostCard.svelte
<script lang="ts">
/* eslint-disable @typescript-eslint/no-explicit-any */
import { format } from 'date-fns';

interface Post {
	frontmatter: {
		title: string;
		date: string;
		tags?: string[];
		excerpt?: string;
		[key: string]: unknown;
	};
	fields: {
		slug: string;
	};
	excerpt?: string;
	timeToRead?: number;
}

interface Props {
	post: Post;
	large?: boolean;
}

let { post, large = false }: Props = $props();

let date = $derived(new Date(post.frontmatter.date));
let datetime = $derived(format(date, 'yyyy-MM-dd'));
let displayDatetime = $derived(format(date, 'dd LLL yyyy'));
</script>

<article class="post-card" class:post-card-large={large}>
	<!-- eslint-disable svelte/no-navigation-without-resolve -->
	<div class="post-card-content">
		<a class="post-card-content-link" href={post.fields.slug}>
			<header class="post-card-header">
				{#if post.frontmatter.tags}
					<div class="post-card-primary-tag">
						{post.frontmatter.tags[0]}
					</div>
				{/if}
				<h2 class="post-card-title">{post.frontmatter.title}</h2>
			</header>
			<section class="post-card-excerpt">
				<p>{post.frontmatter.excerpt || post.excerpt}</p>
			</section>
		</a>
		<footer class="post-card-meta">
			<div class="post-card-byline-content">
				<span class="post-card-byline-date">
					<time {datetime}>{displayDatetime}</time>
					<span class="bull">&bull;</span>
					{post.timeToRead} min read
				</span>
			</div>
		</footer>
	</div>
</article>

<style>
	.post-card {
		position: relative;
		flex: 1 1 301px;
		display: flex;
		flex-direction: column;
		overflow: hidden;
		margin: 0 0 40px;
		padding: 0 20px 40px;
		min-height: 220px;
		border-bottom: 1px solid #eef2f4; /* lighten('0.12', colors.lightgrey) */
		background-size: cover;
	}

	:global(.dark) .post-card {
		border-bottom-color: #2b2d31; /* lighten('0.08', colors.darkmode) approx */
	}

	@media (prefers-color-scheme: dark) {
		.post-card {
			border-bottom-color: #2b2d31;
		}
	}

	@media (min-width: 795px) {
		.post-card-large {
			flex: 1 1 100%;
			flex-direction: row;
			padding-bottom: 40px;
			min-height: 280px;
			border-top: 0;
		}

		.post-card-large :global(.post-card-header) {
			margin-top: 0;
		}

		.post-card-large .post-card-content {
			flex: 0 1 361px;
			justify-content: center;
		}

		.post-card-large .post-card-title {
			margin-top: 0;
			font-size: 3.2rem;
		}

		.post-card-large .post-card-content-link {
			padding: 0 0 0 40px;
		}

		.post-card-large .post-card-meta {
			padding: 0 0 0 40px;
		}

		.post-card-large .post-card-excerpt p {
			margin-bottom: 1.5em;
			font-size: 1.8rem;
			line-height: 1.5em;
		}
	}

	.post-card-content {
		flex-grow: 1;
		display: flex;
		flex-direction: column;
	}

	.post-card-content-link {
		position: relative;
		display: block;
		color: var(--darkgrey);
	}

	.post-card-content-link:hover {
		text-decoration: none;
	}

	.post-card-primary-tag {
		margin: 0 0 0.2em;
		color: var(--green);
		font-size: 1.2rem;
		font-weight: 500;
		letter-spacing: 0.2px;
		text-transform: uppercase;
	}

	.post-card-title {
		margin: 0 0 0.4em;
		line-height: 1.15em;
		transition: color 0.2s ease-in-out;
	}

	@media (prefers-color-scheme: dark) {
		.post-card-title {
			color: rgba(255, 255, 255, 0.85);
		}
	}

	.post-card-excerpt {
		font-family: Georgia, serif;
	}

	@media (prefers-color-scheme: dark) {
		.post-card-excerpt {
			color: #8da1aa !important; /* lighten('0.1', colors.midgrey) */
		}
	}

	.post-card-meta {
		display: flex;
		align-items: flex-start;
		padding: 0;
	}

	.post-card-byline-content {
		flex: 1 1 50%;
		display: flex;
		flex-direction: column;
		margin: 4px 0 0 10px;
		color: #8da1aa; /* lighten('0.1', colors.midgrey) */
		font-size: 1.2rem;
		line-height: 1.4em;
		font-weight: 400;
		letter-spacing: 0.2px;
		text-transform: uppercase;
	}

	.post-card-byline-content span {
		margin: 0;
	}
</style>
